
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "build successful"
  deployStgaing:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "deploy successful"
  deployProduction:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "deploy successful"

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
#              only: master
              ignore: dev1
            tags:
              only: v1.0
      - build:
          requires:
            - test
      - waitForConfirmToStaging:
          type: approval
          requires:
            - build
      - waitForConfirmProduction:
          type: approval
          requires:
            - build
      - deployStgaing:
          requires:
            - waitForConfirmToStaging
      - deployProduction:
          requires:
            - waitForConfirmProduction
