only-version-tag: &only-tag
  tags:
    only:
      - v1.6
      - v1.7
      - v1.9
    ignore: v1.8
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "build successful"
  deployStgaing:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "deploy successful"
  deployProduction:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "deploy successful"
  cron-test1:
    docker:
      - image: circleci/node:10
    steps:
      - run: curl $API_URL
  cron-test2:
    docker:
      - image: circleci/node:10
    steps:
      - run: curl $API_URL
  cron-test3:
    docker:
      - image: circleci/node:10
    steps:
      - run: curl $API_URL
workflows:
  version: 2
#  nightly:
#    triggers:
#      - schedule:
#          cron: "* * * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - cron-test:
#          context: test1
  test-build-deploy:
    jobs:
      - cron-test1:
          context: test1
      - cron-test2:
          context: test2
      - cron-test3
#      - test:
#          filters:
#            branches:
##              only: master
#              ignore: dev1
#            <<: *only-tag
#      - build:
#          requires:
#            - test
#          filters:
#            <<: *only-tag
#      - waitForConfirmToStaging:
#          type: approval
#          requires:
#            - build
#          filters:
#            <<: *only-tag
#      - waitForConfirmProduction:
#          type: approval
#          requires:
#            - build
#          filters:
#            <<: *only-tag
#      - deployStgaing:
#          requires:
#            - waitForConfirmToStaging
#          filters:
#            <<: *only-tag
#      - deployProduction:
#          requires:
#            - waitForConfirmProduction
#          filters:
#            <<: *only-tag

